### ISSUE TITLE
Wrong command on settings

### ISSUE THREAD

**Issue by agorer** [pghilardi/atom-python-test#31]
After updating to 1.0.0 there is the old `atom-python-test:close-panel` command in the package settings instead of the new `atom-python-test:toggle-test-results`.

![image](https://user-images.githubusercontent.com/993205/75525321-f2a30280-5a0f-11ea-882a-d4cdb85d11ca.png)

**Comment by pghilardi** [comment]
Thanks man! I am working on this!

**Comment by pghilardi** [comment]
Check on version 1.0.1
