### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by ssbarnea** [pghilardi/atom-python-test#5]
Tried is on MacOS and got this ugly error while py.test is installed 

The default way to call py.test is via the module invocation: `python -m pytest` as this works on all platforms and also allows you to use it with the default python interpretor.

If someone is trying to call the shell script approach they are locked into using a single version of py.test.
<img width="460" alt="screenshot 2016-07-23 11 59 20" src="https://cloud.githubusercontent.com/assets/102495/17077605/4824b7d0-50cd-11e6-8162-c5aeef887688.png">

**Comment by pghilardi** [comment]
Hello ssbarnea!

I have published a new version with the default py.test command mapping to "python -m pytest". I searched in the internet and it seems that MacOS users have problems running the command py.test.

So, just update to the last version which is 0.2.0.

Thanks!

**Comment by pghilardi** [comment]
Update to the version 0.2.1.

**Comment by rubencabrera** [comment]
Hitting this on 0.10.0
