### ISSUE TITLE
Run doctests in file

### ISSUE THREAD

**Issue by adamboche** [pghilardi/atom-python-test#6]
It would be great if the package could detect and run any doctests in the file, and report the output regularly. Pytest has doctest integration, discussed here: http://doc.pytest.org/en/latest/doctest.html

**Comment by pghilardi** [comment]
Hello @adamboche ,

I added a configuration to execute doc tests on test runs. By default this configuration will be false, i.e, will not run doctests, but you can edit it to true going to "Settings" and then "Atom Python Test" and checking it to include doctests on test runs.

Update your plug-in to the last version (0.5.0) to get this feature.

Thanks
